import {
  FACTORY_ADDRESS,
  POOL_ADDRESS,
  ROUTER_ADDRESS,
  PM_ADDRESS,
  PROFILE_CONTRACT_ADDRESS,
} from "@/config/contracts";

export {
  FACTORY_ADDRESS,
  POOL_ADDRESS,
  ROUTER_ADDRESS,
  PM_ADDRESS,
  PROFILE_CONTRACT_ADDRESS,
};
